# Generated by Django 5.0.6 on 2024-07-03 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=50, verbose_name='product name')),
                ('old_price', models.FloatField()),
                ('price', models.FloatField()),
                ('category', models.IntegerField(choices=[(1, 'New launch'), (2, 'Tranding Near you'), (3, 'Frequentally use')], verbose_name='categeory')),
                ('sub_category', models.IntegerField(choices=[(1, 'Personal care'), (2, 'Health food and drinks'), (3, 'Beauty'), (4, 'Skin care'), (5, 'Home care'), (6, 'Must have'), (7, 'Health condition'), (8, 'Sexsual wellness')], verbose_name='sub_categeory')),
                ('description', models.CharField(max_length=300, verbose_name='details')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_available')),
                ('pimage', models.ImageField(upload_to='image')),
            ],
        ),
    ]
